# Generated by Django 4.1.7 on 2023-03-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_appointment_client_name_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(related_name='category', to='news.author'),
        ),
    ]
