# Generated by Django 4.1.7 on 2023-04-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_category_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subscribers',
        ),
    ]
